### PR TITLE
Adding support for list arguments

### PR DESCRIPTION
**Pull request by jivemonkey**
Just contributing back changes I made to support list argument.

### CODE REVIEW

**Comment by thomaschaplin** [comment]
@jivemonkey thank you for contributing!

**Comment by thomaschaplin** [comment]
@jivemonkey I will review this in-depth today but it looks like some of the pipeline is failing (please ignore the `Ticket ID` job). I believe `array.flatmap()` was introduced in node v11 hence why it fails in v10

**Comment by thomaschaplin** [comment]
I have another PR open which updates our pipeline to use newer versions of NodeJS - https://github.com/trayio/graphql-query-to-json/pull/10

@jivemonkey sorry for the inconvenience but please could you merge in master once my PR has been merged?

**Comment by thomaschaplin** [comment]
@jivemonkey this PR is good - I just need to resolve an issue we are seeing with our `Dependency audit` job.

Leave this with me, I will get this fixed soon and provide an update via comment

**Comment by jivemonkey** [comment]
Thanks @thomaschaplin let me know if there is anything else I should do.

**Comment by thomaschaplin** [comment]
> Thanks @thomaschaplin let me know if there is anything else I should do.

Nope, all good on your side! I just need to make an adjustment to our `Dependency audit` job.
I will get this fixed soon and let you know so we can get this merged in

**Review by thomaschaplin — APPROVED** [review]

**Comment by thomaschaplin** [comment]
Thank you for your work on this PR @jivemonkey - much appreciated from the tray.io team! 🎉

**Comment by thomaschaplin** [comment]
We have now published a new version - `1.1.0`

https://www.npmjs.com/package/graphql-query-to-json

Thanks again for your support @jivemonkey

**Pull request merged**
